/**
 * Persistencia de drafts de Job Profile (post-reunión cliente).
 *
 * La tabla `JobProfileDrafts` es OPCIONAL (deferred Block 2). Si no existe, los
 * endpoints devuelven 503 con un mensaje claro.
 *
 * Endpoints:
 *   POST  /api/drafts/jobs/save         → persiste el draft generado por IA
 *   GET   /api/drafts/jobs              → lista drafts del tenant
 *   GET   /api/drafts/jobs/:id          → obtiene un draft
 *   PATCH /api/drafts/jobs/:id          → actualiza status/draft_payload (regeneración manual)
 *   POST  /api/drafts/jobs/:id/convert  → crea Job real desde el draft + linkea draft.job_id
 *
 * Esto NO incluye el flow del portal cliente (approve / request-changes desde el lado del cliente).
 * Eso requiere endpoints públicos con token kind='portal' que validen el draft pertenece al portal,
 * y se hace en otra tanda.
 */
import type { IncomingMessage } from 'http';
import type { RequestContext } from '../lib/context';
import { datastore, zcql, now } from '../lib/db';
import { escapeSql, unwrapRow, unwrapRows } from '../lib/dbHelpers';
import { stringifyAndTruncate, FIELD_LIMITS } from '../lib/dbLimits';
import { persistLargeContent, persistLargeJson, loadLargeContent, loadLargeJson, deleteLargeContent } from '../lib/largeContentStore';
import { NotFoundError, ValidationError, AppError } from '../lib/errors';
import { sendJson, readJsonBody } from '../lib/http';
import { logger } from '../lib/logger';
import { requireAuth } from '../lib/auth';
import { env } from '../lib/env';
import { requireTenant } from './tenants';
import { auditLog } from '../lib/auditLog';

const log = logger('JOB_DRAFTS');
const TABLE = 'JobProfileDrafts';

export type DraftStatus =
  | 'draft_generated'
  | 'pending_client_review'
  | 'client_approved'
  | 'client_changes_requested'
  | 'converted_to_job'
  | 'discarded';

export type JobProfileDraftRow = {
  ROWID: string;
  tenant_id: string;
  transcript: string | null;
  transcript_source: string;
  meeting_url: string | null;
  draft_payload: string;
  status: DraftStatus;
  version: number;
  highlights: string | null;
  created_by: string;
  client_email: string | null;
  client_approved_at: string | null;
  job_id: string | null;
  created_at: string;
  updated_at: string;
};

const TABLE_NOT_READY = new AppError(
  503,
  'table_not_ready',
  `La tabla ${TABLE} todavía no fue creada. Crear en Catalyst Console (ver MIGRATIONS_BLOCK2.md §4) y reintentar.`,
);

async function isTableReady(req: IncomingMessage): Promise<boolean> {
  try {
    await zcql(req).executeZCQLQuery(`SELECT ROWID FROM ${TABLE} LIMIT 1`);
    return true;
  } catch (err) {
    log.warn('table not ready', { error: (err as Error).message });
    return false;
  }
}

function extractIdFromPath(url: string, suffix = ''): string | null {
  const re = suffix
    ? new RegExp(`^/api/drafts/jobs/([^/]+)${suffix}/?$`)
    : /^\/api\/drafts\/jobs\/([^/]+)\/?$/;
  return url.match(re)?.[1] ?? null;
}

function validateStatus(s: unknown): DraftStatus {
  const allowed: DraftStatus[] = [
    'draft_generated', 'pending_client_review', 'client_approved',
    'client_changes_requested', 'converted_to_job', 'discarded',
  ];
  if (typeof s !== 'string' || !allowed.includes(s as DraftStatus)) {
    throw new ValidationError(`status must be one of ${allowed.join(', ')}`);
  }
  return s as DraftStatus;
}

// ===== Handlers =====

export async function saveJobDraft(ctx: RequestContext): Promise<void> {
  await requireAuth(ctx);
  const tenantId = await requireTenant(ctx);
  if (!(await isTableReady(ctx.req))) throw TABLE_NOT_READY;

  const body = await readJsonBody<Record<string, unknown>>(ctx.req);
  if (!body.draft_payload || typeof body.draft_payload !== 'object') {
    throw new ValidationError('draft_payload required (object generated by /api/drafts/generate)');
  }
  const transcript = typeof body.transcript === 'string' ? body.transcript : null;
  const transcriptSource = typeof body.transcript_source === 'string' ? body.transcript_source : 'manual';
  const status: DraftStatus = body.status !== undefined ? validateStatus(body.status) : 'draft_generated';
  const version = typeof body.version === 'number' ? body.version : 1;
  const clientEmail = typeof body.client_email === 'string' ? body.client_email.trim().slice(0, 255) : null;
  const meetingId = typeof body.meeting_url === 'string' ? body.meeting_url.slice(0, 255) : null;
  const highlights = body.highlights !== undefined
    ? stringifyAndTruncate(body.highlights, FIELD_LIMITS.DRAFT_HIGHLIGHTS, 'JobProfileDrafts.highlights')
    : null;

  // Extraer client_name + client_company del draft_payload generado por la IA
  // (la tabla los tiene como columnas separadas, los persistimos para queries rápidas).
  const draftObj = body.draft_payload as Record<string, unknown>;
  const clientName = typeof draftObj.title === 'string' ? draftObj.title.slice(0, 255) : null;
  const clientCompany = typeof draftObj.company === 'string' ? draftObj.company.slice(0, 255) : null;

  let transcriptStored: string | null = null;
  let draftPayloadStored: string;
  try {
    transcriptStored = transcript != null
      ? await persistLargeContent(ctx.req, transcript, 'JobProfileDrafts.transcript')
      : null;
    draftPayloadStored = await persistLargeJson(ctx.req, body.draft_payload, 'JobProfileDrafts.draft_payload');
  } catch (err) {
    log.error('saveJobDraft: persistLargeContent failed', {
      traceId: ctx.traceId,
      step: 'persist_large_content',
      name: (err as Error).name,
      message: (err as Error).message,
      stack: (err as Error).stack?.split('\n').slice(0, 5).join(' | '),
    });
    throw new AppError(500, 'save_failed_persist', `Save fail (persist): ${(err as Error).message}`);
  }

  const insert: Record<string, unknown> = {
    tenant_id: tenantId,
    transcript: transcriptStored,
    transcript_source: transcriptSource,
    draft_payload: draftPayloadStored,
    status,
    version,
    highlights,
    client_email: clientEmail,
    client_name: clientName,
    client_company: clientCompany,
    meeting_id: meetingId,
    job_id: null,
    created_at: now(),
    updated_at: now(),
  };

  let saved: JobProfileDraftRow | null;
  try {
    const row = await datastore(ctx.req).table(TABLE).insertRow(insert);
    saved = unwrapRow<JobProfileDraftRow>(row, TABLE);
  } catch (err) {
    // Catalyst a veces tira objetos planos sin .message — serializamos todo el err
    // para no perder info en el response/log.
    const errAny = err as unknown as Record<string, unknown>;
    const errMsg = (err as Error)?.message
      || (errAny?.error as string)
      || (errAny?.code as string)
      || JSON.stringify(err).slice(0, 500);
    const errName = (err as Error)?.name || 'unknown';
    log.error('saveJobDraft: insertRow failed', {
      traceId: ctx.traceId,
      step: 'insert_row',
      table: TABLE,
      name: errName,
      message: errMsg,
      stack: (err as Error)?.stack?.split('\n').slice(0, 5).join(' | '),
      raw_error: JSON.stringify(err).slice(0, 1000),
      insert_keys: Object.keys(insert),
      insert_types: Object.fromEntries(Object.entries(insert).map(([k, v]) => [k, v === null ? 'null' : typeof v])),
    });
    // Si falla la inserción, limpiar los File Store refs que ya subimos
    deleteLargeContent(ctx.req, transcriptStored).catch(() => {});
    deleteLargeContent(ctx.req, draftPayloadStored).catch(() => {});
    throw new AppError(500, 'save_failed_insert', `Save fail (insert): ${errMsg}`);
  }

  void auditLog(ctx, {
    action: 'draft.generate',
    resource_type: 'job_profile_draft',
    resource_id: saved?.ROWID ?? null,
    changes: { status, version, has_transcript: transcript != null },
  });

  log.info('draft saved', { traceId: ctx.traceId, tenantId, draftId: saved?.ROWID, status });
  sendJson(ctx.res, 201, { draft: saved });
}

export async function listJobDrafts(ctx: RequestContext): Promise<void> {
  await requireAuth(ctx);
  const tenantId = await requireTenant(ctx);
  if (!(await isTableReady(ctx.req))) throw TABLE_NOT_READY;

  const url = new URL(ctx.req.url ?? '/', 'http://x');
  const status = url.searchParams.get('status');
  const filters = [`tenant_id = '${escapeSql(tenantId)}'`];
  if (status) {
    filters.push(`status = '${escapeSql(status)}'`);
  }

  const query = `SELECT * FROM ${TABLE} WHERE ${filters.join(' AND ')} ORDER BY CREATEDTIME DESC`;
  const rows = unwrapRows<JobProfileDraftRow>(
    (await zcql(ctx.req).executeZCQLQuery(query)) as unknown[],
    TABLE,
  );

  sendJson(ctx.res, 200, { drafts: rows, count: rows.length });
}

export async function getJobDraft(ctx: RequestContext): Promise<void> {
  await requireAuth(ctx);
  const tenantId = await requireTenant(ctx);
  if (!(await isTableReady(ctx.req))) throw TABLE_NOT_READY;
  const id = extractIdFromPath(ctx.req.url ?? '/');
  if (!id) throw new ValidationError('draft id missing');

  const draft = await fetchDraft(ctx.req, id, tenantId);
  if (!draft) throw new NotFoundError(`Draft ${id} not found`);

  // Resolver File Store refs para que el frontend reciba contenido real
  const resolved: JobProfileDraftRow = {
    ...draft,
    transcript: await loadLargeContent(ctx.req, draft.transcript),
    draft_payload: (await loadLargeContent(ctx.req, draft.draft_payload)) ?? draft.draft_payload,
  };
  sendJson(ctx.res, 200, { draft: resolved });
}

export async function patchJobDraft(ctx: RequestContext): Promise<void> {
  await requireAuth(ctx);
  const tenantId = await requireTenant(ctx);
  if (!(await isTableReady(ctx.req))) throw TABLE_NOT_READY;
  const id = extractIdFromPath(ctx.req.url ?? '/');
  if (!id) throw new ValidationError('draft id missing');

  const existing = await fetchDraft(ctx.req, id, tenantId);
  if (!existing) throw new NotFoundError(`Draft ${id} not found`);

  const body = await readJsonBody<Record<string, unknown>>(ctx.req);
  const patch: Record<string, unknown> = { ROWID: id, updated_at: now() };

  if (body.status !== undefined) patch.status = validateStatus(body.status);
  // NOTA: NO permitimos patchear draft_payload via PATCH. El payload se persiste UNA
  // VEZ con saveJobDraft (que recibe el JSON original generado por la IA). Si se
  // permite patchearlo después, el frontend admin puede sobreescribirlo con un shape
  // adaptado (subset del original) y se pierden los campos narrativos (objetivo_cargo,
  // responsabilidades, disc_perfil_descripcion, etc.) que el portal del cliente
  // necesita mostrar. Si alguien manda draft_payload en el body, lo IGNORAMOS y
  // logueamos warning para detectar callers que lo intenten.
  if (body.draft_payload !== undefined) {
    log.warn('patchJobDraft: draft_payload in body ignored (use save endpoint to overwrite)', {
      traceId: ctx.traceId, draftId: id,
    });
  }
  if (body.version !== undefined && typeof body.version === 'number') {
    patch.version = body.version;
  }
  if (body.highlights !== undefined) {
    patch.highlights = stringifyAndTruncate(body.highlights, FIELD_LIMITS.DRAFT_HIGHLIGHTS, 'JobProfileDrafts.highlights');
  }
  // client_approved_at no se persiste — la tabla actual no tiene esa columna.
  // El status='client_approved' es suficiente; si se necesita timestamp, se infiere
  // de MODIFIEDTIME cuando status cambió.

  const row = await datastore(ctx.req).table(TABLE).updateRow(patch as { ROWID: string });
  const updated = unwrapRow<JobProfileDraftRow>(row, TABLE);

  void auditLog(ctx, {
    action: 'draft.refine',
    resource_type: 'job_profile_draft',
    resource_id: id,
    changes: { status: patch.status, version: patch.version },
  });

  sendJson(ctx.res, 200, { draft: updated });
}

/**
 * Convierte un draft en un Job real.
 *
 *   POST /api/drafts/jobs/:id/convert
 *
 * Crea Job con title/company/cognitive_level/ideal_profile derivados del draft_payload,
 * marca el draft como `converted_to_job` y le linkea job_id.
 */
export async function convertDraftToJob(ctx: RequestContext): Promise<void> {
  await requireAuth(ctx);
  const tenantId = await requireTenant(ctx);
  if (!(await isTableReady(ctx.req))) throw TABLE_NOT_READY;
  const id = extractIdFromPath(ctx.req.url ?? '/', '/convert');
  if (!id) throw new ValidationError('draft id missing');

  const draft = await fetchDraft(ctx.req, id, tenantId);
  if (!draft) throw new NotFoundError(`Draft ${id} not found`);

  const result = await convertDraftInternal(ctx, draft, tenantId, {
    createdBy: ctx.user?.clerk_user_id ?? '',
  });

  sendJson(ctx.res, 201, { job_id: result.jobId, draft_id: id });
}

/**
 * Lógica core de "convertir draft a Job". Reutilizable desde:
 *   - `convertDraftToJob` (admin via /api/drafts/jobs/:id/convert)
 *   - `approveDraftPublic` (cliente aprueba via /portal/<token>/drafts/:id/approve)
 *
 * Idempotente: si el draft ya está convertido (job_id no-null), devuelve ese job_id
 * sin re-crear nada. Esto evita doble-creación si el cliente o el admin disparan
 * el flow más de una vez.
 */
async function convertDraftInternal(
  ctx: RequestContext,
  draft: JobProfileDraftRow,
  tenantId: string,
  opts: { createdBy: string },
): Promise<{ jobId: string }> {
  // Idempotency: si ya está convertido, devolver el job_id existente
  if (draft.job_id) {
    log.info('convertDraftInternal: already converted, skipping', {
      traceId: ctx.traceId, draftId: draft.ROWID, jobId: draft.job_id,
    });
    return { jobId: draft.job_id };
  }

  let payload: Record<string, unknown>;
  try {
    const loaded = await loadLargeJson<Record<string, unknown>>(ctx.req, draft.draft_payload);
    if (!loaded) throw new Error('empty');
    payload = loaded;
  } catch {
    throw new ValidationError('draft_payload no es JSON válido');
  }

  const title = typeof payload.title === 'string' ? payload.title.trim() : '';
  const draftAny = draft as Record<string, unknown>;
  const companyFromPayload = typeof payload.company === 'string' ? payload.company.trim() : '';
  const companyFromRow = typeof draftAny.client_company === 'string' ? (draftAny.client_company as string).trim() : '';
  const company = companyFromPayload || companyFromRow || 'Cliente sin nombre';
  if (!title) throw new ValidationError('draft.title vacío — no se puede crear Job');

  const idealProfile: Record<string, unknown> = {};
  if (payload.disc_ideal && typeof payload.disc_ideal === 'object') {
    const d = payload.disc_ideal as Record<string, unknown>;
    idealProfile.disc = {
      d: Number(d.d) || 0, i: Number(d.i) || 0, s: Number(d.s) || 0, c: Number(d.c) || 0,
    };
  }
  if (payload.velna_ideal && typeof payload.velna_ideal === 'object') {
    idealProfile.velna = payload.velna_ideal;
  }
  if (Array.isArray(payload.competencias)) {
    idealProfile.competencias = payload.competencias;
  }
  if (typeof payload.tecnica_minimo_pct === 'number') {
    idealProfile.tecnica_minimo_pct = payload.tecnica_minimo_pct;
  }
  if (typeof payload.context_summary === 'string') {
    idealProfile.context_summary = payload.context_summary;
  }

  const cognitiveLevel = (typeof payload.cognitive_level === 'string'
    ? payload.cognitive_level
    : 'mid') as 'basic' | 'mid' | 'senior';

  const jobInsert = {
    tenant_id: tenantId,
    title: title.slice(0, 255),
    company: company.slice(0, 255),
    tech_prompt: typeof payload.tech_prompt_seed === 'string' ? payload.tech_prompt_seed : null,
    cognitive_level: cognitiveLevel,
    is_active: true,
    company_context: typeof payload.context_summary === 'string' ? payload.context_summary : null,
    created_by: opts.createdBy,
    created_at: now(),
    updated_at: now(),
    ...(Object.keys(idealProfile).length > 0 ? { ideal_profile: JSON.stringify(idealProfile) } : {}),
  };

  const jobRow = await datastore(ctx.req).table('Jobs').insertRow(jobInsert);
  const job = unwrapRow<{ ROWID: string }>(jobRow, 'Jobs');
  if (!job) throw new AppError(500, 'job_create_failed', 'No se pudo crear el Job desde el draft');

  await datastore(ctx.req).table(TABLE).updateRow({
    ROWID: draft.ROWID,
    status: 'converted_to_job',
    job_id: job.ROWID,
    updated_at: now(),
  });

  void auditLog(ctx, {
    action: 'job.create',
    resource_type: 'job',
    resource_id: job.ROWID,
    changes: { from_draft: draft.ROWID, title, company },
  });

  log.info('draft converted to job', { traceId: ctx.traceId, draftId: draft.ROWID, jobId: job.ROWID });

  // Sync con Zoho Recruit: crear Job_Opening espejo. Fire-and-forget — si falla,
  // el Job ya quedó creado en SharkTalents y se puede re-sincronizar manualmente.
  void syncJobToRecruit(ctx, { jobId: job.ROWID, title, company, payload });

  return { jobId: job.ROWID };
}

async function syncJobToRecruit(
  ctx: RequestContext,
  input: { jobId: string; title: string; company: string; payload: Record<string, unknown> },
): Promise<void> {
  try {
    const { isZohoRecruitConfigured, createRecruitJobOpening, updateRecruitJobOpening } = await import('../lib/zohoRecruitClient.js');
    if (!isZohoRecruitConfigured()) {
      log.info('recruit sync skipped — not configured', { jobId: input.jobId });
      return;
    }
    const salary = (() => {
      const range = input.payload.salary_range_usd as { min?: number; max?: number } | undefined;
      if (!range || (!range.min && !range.max)) return undefined;
      return `${range.min ?? 0}-${range.max ?? 0} USD`;
    })();
    const description = buildJobDescriptionHtml(input.payload);

    // Paso 1: crear el Job Opening (sin los campos custom porque necesitamos el recruit_id
    // para construir las URLs de las pruebas).
    const result = await createRecruitJobOpening({
      Job_Opening_Name: input.title,
      Posting_Title: input.title,
      Client_Name: input.company,
      Job_Description: description,
      Salary: salary,
      Job_Opening_Status: 'In-progress',
      // Publicar en el career site de Kuno Talentos (sino el puesto se crea pero queda invisible).
      customFields: { Publish: true, Keep_on_Career_Site: true },
    }, ctx.traceId);
    if (!result.ok) {
      log.warn('recruit job opening create failed', { jobId: input.jobId, error: result.error });
      return;
    }
    const recruitId = result.data.data?.[0]?.details?.id ?? '';
    if (!recruitId) {
      log.warn('recruit job opening created but no id returned', { jobId: input.jobId });
      return;
    }

    // Paso 2: persistir recruit_id en SharkTalents (Jobs.recruit_job_id)
    try {
      await datastore(ctx.req).table('Jobs').updateRow({
        ROWID: input.jobId, recruit_job_id: recruitId, updated_at: now(),
      });
      log.info('recruit job opening created + linked', { jobId: input.jobId, recruitId });
    } catch (err) {
      log.warn('Jobs.recruit_job_id column may not exist; opening created but not linked', {
        jobId: input.jobId, recruitId, error: (err as Error).message,
      });
    }

    // Paso 3: llenar los campos custom del Job Opening en Recruit con los links de pruebas.
    // Los links apuntan al endpoint `/api/recruit/test-link` que automáticamente identifica
    // candidato + job y redirige al test correspondiente sin que el candidato re-ingrese datos.
    const e = env();
    const baseUrl = `${e.APP_BASE_URL.replace(/\/$/, '')}/server/api/api/recruit/test-link?recruit_job_id=${recruitId}`;
    // API names sincronizados con la UI (Cris renombró los API names en 2026-05-17).
    const customFieldsUpdate: Record<string, unknown> = {
      Perfil_Disc: `${baseUrl}&phase=disc`,
      Perfil_Tecnica: `${baseUrl}&phase=tecnica`,
      Prueba_Integridad: `${baseUrl}&phase=integridad`,
      // Rich text: Requisitos (formación + experiencia + herramientas)
      ...(buildRequisitosHtml(input.payload) ? { Requisitos: buildRequisitosHtml(input.payload) } : {}),
      // Rich text: Ventajas (DISC ventajas + salario + modalidad)
      ...(buildVentajasHtml(input.payload) ? { Ventajas: buildVentajasHtml(input.payload) } : {}),
    };
    const updateResult = await updateRecruitJobOpening(recruitId, customFieldsUpdate, ctx.traceId);
    if (!updateResult.ok) {
      log.warn('recruit job opening custom-fields update failed — API names may differ', {
        jobId: input.jobId, recruitId, error: updateResult.error,
        attempted_fields: Object.keys(customFieldsUpdate),
      });
    } else {
      log.info('recruit job opening custom fields populated', { jobId: input.jobId, recruitId });
    }
  } catch (err) {
    log.warn('recruit sync failed', { jobId: input.jobId, error: (err as Error).message });
  }
}

/**
 * Admin envía el draft al cliente para validación.
 *
 *   POST /api/drafts/jobs/:id/send-to-client
 *   Body opcional: { client_email?: string }  — override del email guardado en el draft
 *
 * Genera portal token (kind='portal'), marca status='pending_client_review' y
 * encola email vía ZeptoMail con el link al portal del draft.
 */
export async function sendDraftToClient(ctx: RequestContext): Promise<void> {
  await requireAuth(ctx);
  const tenantId = await requireTenant(ctx);
  if (!(await isTableReady(ctx.req))) throw TABLE_NOT_READY;
  const id = extractIdFromPath(ctx.req.url ?? '/', '/send-to-client');
  if (!id) throw new ValidationError('draft id missing');

  const draft = await fetchDraft(ctx.req, id, tenantId);
  if (!draft) throw new NotFoundError(`Draft ${id} not found`);

  const body = await readJsonBody<{ client_email?: string }>(ctx.req).catch(() => ({} as { client_email?: string }));
  const overrideEmail = typeof body.client_email === 'string' ? body.client_email.trim().toLowerCase() : '';
  const draftAny = draft as Record<string, unknown>;
  const draftClientEmail = typeof draftAny.client_email === 'string' ? (draftAny.client_email as string).trim() : '';
  const clientEmail = overrideEmail || draftClientEmail;
  if (!clientEmail || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(clientEmail)) {
    throw new ValidationError('client_email no válido — proveelo en body o en el draft antes de enviar');
  }

  const draftClientName = typeof draftAny.client_name === 'string' ? (draftAny.client_name as string).trim() : '';
  const draftCompany = typeof draftAny.client_company === 'string' ? (draftAny.client_company as string).trim() : '';

  // Cargar payload para tener el title (lo usamos en el subject del email)
  let payload: Record<string, unknown> = {};
  try {
    const loaded = await loadLargeJson<Record<string, unknown>>(ctx.req, draft.draft_payload);
    if (loaded) payload = loaded;
  } catch { /* ignore */ }
  const jobTitle = typeof payload.title === 'string' ? payload.title : 'Puesto';

  // Cargar nombre de la agencia (el tenant — el slug o name de la agencia)
  let agencyName = 'SharkTalents';
  try {
    const { unwrapRows: unr } = await import('../lib/dbHelpers.js');
    const tenantRows = unr<{ name?: string }>(
      (await zcql(ctx.req).executeZCQLQuery(
        `SELECT name FROM Tenants WHERE ROWID = '${escapeSql(tenantId)}' LIMIT 1`,
      )) as unknown[],
      'Tenants',
    );
    if (tenantRows[0]?.name) agencyName = String(tenantRows[0].name);
  } catch { /* keep default */ }

  // Generar portal token. ref = tenant_id (no draft_id) porque ese es el contrato
  // del token según signPortalToken (revisar lib/clientPortalTokens.ts).
  const { signPortalToken } = await import('../lib/clientPortalTokens.js');
  const portalToken = signPortalToken({
    ref: tenantId,
    company: draftCompany || 'Cliente',
    client_name: draftClientName || 'Cliente',
    client_email: clientEmail,
    agency_name: agencyName,
    ttl_days: 30,
  });

  const e = env();
  const portalUrl = `${e.APP_BASE_URL.replace(/\/$/, '')}/app/#/portal/${portalToken}/draft/${id}`;

  // Marcar draft como pending_client_review.
  // Si el caller pasó un client_email distinto al guardado, lo persistimos también
  // para que futuros sends/comentarios usen el nuevo correo.
  const draftUpdate: Record<string, unknown> = {
    ROWID: id,
    status: 'pending_client_review',
    updated_at: now(),
  };
  if (overrideEmail && overrideEmail !== draftClientEmail.toLowerCase()) {
    draftUpdate.client_email = clientEmail;
  }
  await datastore(ctx.req).table(TABLE).updateRow(draftUpdate as { ROWID: string });

  // Encolar email y procesarlo EN EL MISMO REQUEST. publishAndProcessEvent llama al
  // dispatcher inmediatamente; si falla, el evento queda en pending para retry posterior.
  // Así el email llega al cliente al instante en vez de esperar al cron manual.
  try {
    const { publishAndProcessEvent } = await import('./outbox.js');
    const result = await publishAndProcessEvent(ctx.req, 'email.send_pending', {
      to: clientEmail,
      template: 'client_draft_review',
      locale: 'es',
      vars: {
        client_name: draftClientName || 'equipo',
        agency_name: agencyName,
        job_title: jobTitle,
        company: draftCompany || '',
        portal_url: portalUrl,
      },
    });
    if (!result.ok) {
      log.warn('client draft review email queued but dispatch failed', { error: result.error, draftId: id });
    } else {
      log.info('client draft review email sent immediately', { draftId: id, eventId: result.id });
    }
  } catch (err) {
    log.warn('failed to enqueue client draft review email', { error: (err as Error).message, draftId: id });
  }

  void auditLog(ctx, {
    action: 'draft.send_to_client',
    resource_type: 'job_profile_draft',
    resource_id: id,
    changes: { client_email: clientEmail, portal_url_generated: true },
  });

  log.info('draft sent to client', { traceId: ctx.traceId, draftId: id, clientEmail: clientEmail.split('@')[0] + '@…' });
  sendJson(ctx.res, 200, { ok: true, status: 'pending_client_review', portal_url: portalUrl });
}

/**
 * Endpoint público: el cliente ve el draft desde el portal.
 *
 *   GET /portal/:token/drafts/:id
 *
 * Auth: portal token (kind='portal'). Devuelve datos del draft + datos del cliente
 * (sin info sensible interna).
 */
export async function getDraftPublic(ctx: RequestContext): Promise<void> {
  const match = ctx.req.url?.match(/^\/portal\/([^/]+)\/drafts\/([^/]+)\/?(?:\?.*)?$/);
  const [, token, draftId] = match ?? [];
  if (!token || !draftId) throw new ValidationError('path inválido');

  let claims;
  try {
    const { verifyPortalToken } = await import('../lib/clientPortalTokens.js');
    claims = verifyPortalToken(token);
  } catch {
    throw new AppError(401, 'unauthorized', 'Portal token inválido o expirado');
  }

  if (!(await isTableReady(ctx.req))) throw TABLE_NOT_READY;

  const q = `SELECT * FROM ${TABLE} WHERE ROWID = '${escapeSql(draftId)}' LIMIT 1`;
  const rows = unwrapRows<JobProfileDraftRow>(
    (await zcql(ctx.req).executeZCQLQuery(q)) as unknown[],
    TABLE,
  );
  const draft = rows[0];
  if (!draft) throw new NotFoundError(`Draft ${draftId} not found`);

  if (claims.ref !== draft.tenant_id) {
    throw new AppError(403, 'forbidden', 'Portal token no pertenece al tenant del draft');
  }

  let payload: Record<string, unknown> = {};
  try {
    const loaded = await loadLargeJson<Record<string, unknown>>(ctx.req, draft.draft_payload);
    if (loaded) payload = loaded;
  } catch { /* ignore */ }

  sendJson(ctx.res, 200, {
    draft: {
      id: draft.ROWID,
      status: draft.status,
      created_at: draft.created_at,
      client_name: claims.client_name,
      client_company: claims.company,
      agency_name: claims.agency_name,
      payload,
    },
  });
}

// ===== Endpoints públicos token-signed (cliente aprueba/rechaza desde portal) =====

/**
 * Cliente aprueba un draft via portal token.
 *
 *   POST /portal/<token>/drafts/<id>/approve
 *   Body opcional: { client_comment?: string }
 *
 * Marca status='client_approved' + client_approved_at=now. Audit log + outbox event
 * para que Cris reciba notificación.
 */
export async function approveDraftPublic(ctx: RequestContext): Promise<void> {
  const match = ctx.req.url?.match(/^\/portal\/([^/]+)\/drafts\/([^/]+)\/approve/);
  const [, token, draftId] = match ?? [];
  if (!token || !draftId) throw new ValidationError('path inválido');

  // Verificar portal token
  let claims;
  try {
    const { verifyPortalToken } = await import('../lib/clientPortalTokens.js');
    claims = verifyPortalToken(token);
  } catch {
    throw new AppError(401, 'unauthorized', 'Portal token inválido o expirado');
  }

  if (!(await isTableReady(ctx.req))) throw TABLE_NOT_READY;

  // Cargar draft (público, sin tenantId — el portal token ya verifica acceso)
  const q = `SELECT * FROM ${TABLE} WHERE ROWID = '${escapeSql(draftId)}' LIMIT 1`;
  const rows = unwrapRows<JobProfileDraftRow>(
    (await zcql(ctx.req).executeZCQLQuery(q)) as unknown[],
    TABLE,
  );
  const draft = rows[0];
  if (!draft) throw new NotFoundError(`Draft ${draftId} not found`);

  // Verificar que el portal token es del mismo tenant que el draft.
  // Portal token guarda tenant_id en claims.ref (ver lib/clientPortalTokens.ts).
  if (claims.ref !== draft.tenant_id) {
    throw new AppError(403, 'forbidden', 'Portal token no pertenece al tenant del draft');
  }

  const body = await readJsonBody<{ client_comment?: string }>(ctx.req).catch(() => ({} as { client_comment?: string }));
  const comment = typeof body.client_comment === 'string' ? body.client_comment.slice(0, 500) : null;

  await datastore(ctx.req).table(TABLE).updateRow({
    ROWID: draftId,
    status: 'client_approved',
    updated_at: now(),
  });

  // Convertir el draft a Job real + sincronizar con Recruit. Idempotente: si ya está
  // convertido (job_id seteado) usa el existente. Si falla, dejamos el draft como
  // 'client_approved' (NO 'converted_to_job') y log warning — Cris puede re-disparar
  // el convert manualmente desde admin.
  let jobId: string | null = null;
  try {
    const result = await convertDraftInternal(ctx, draft, draft.tenant_id, { createdBy: 'client_portal' });
    jobId = result.jobId;
  } catch (err) {
    log.error('approve→convert failed', {
      traceId: ctx.traceId, draftId, error: (err as Error).message,
    });
    // No throw — el approve igual fue exitoso. Cris convierte manual después.
  }

  // Outbox: notificar a Cris
  try {
    const { publishOutboxEvent } = await import('./outbox.js');
    await publishOutboxEvent(ctx.req, 'draft.client_approved', {
      tenant_id: draft.tenant_id,
      draft_id: draftId,
      client_email: draft.client_email,
      client_comment: comment,
      job_id: jobId,
    });
  } catch (err) {
    log.warn('draft approved outbox publish failed', { error: (err as Error).message });
  }

  // Tracking server-side
  void (async () => {
    const { recordPortalSnapshot } = await import('./jobTracking.js');
    await recordPortalSnapshot(ctx, {
      tenantId: draft.tenant_id,
      eventType: 'portal.draft_approved',
      portalToken: token,
      eventData: { draft_id: draftId, has_comment: !!comment, job_id: jobId },
    });
  })();

  log.info('draft approved by client + converted to job', { draftId, tenantId: draft.tenant_id, jobId });
  sendJson(ctx.res, 200, { ok: true, status: 'client_approved', job_id: jobId });
}

/**
 * Cliente rechaza/pide cambios en un draft.
 *
 *   POST /portal/<token>/drafts/<id>/request-changes
 *   Body: { client_comment: string (qué cambiar) }
 */
export async function requestChangesDraftPublic(ctx: RequestContext): Promise<void> {
  const match = ctx.req.url?.match(/^\/portal\/([^/]+)\/drafts\/([^/]+)\/request-changes/);
  const [, token, draftId] = match ?? [];
  if (!token || !draftId) throw new ValidationError('path inválido');

  let claims;
  try {
    const { verifyPortalToken } = await import('../lib/clientPortalTokens.js');
    claims = verifyPortalToken(token);
  } catch {
    throw new AppError(401, 'unauthorized', 'Portal token inválido o expirado');
  }

  if (!(await isTableReady(ctx.req))) throw TABLE_NOT_READY;

  const q = `SELECT * FROM ${TABLE} WHERE ROWID = '${escapeSql(draftId)}' LIMIT 1`;
  const rows = unwrapRows<JobProfileDraftRow>(
    (await zcql(ctx.req).executeZCQLQuery(q)) as unknown[],
    TABLE,
  );
  const draft = rows[0];
  if (!draft) throw new NotFoundError(`Draft ${draftId} not found`);

  // Portal token guarda tenant_id en claims.ref (ver lib/clientPortalTokens.ts).
  if (claims.ref !== draft.tenant_id) {
    throw new AppError(403, 'forbidden', 'Portal token no pertenece al tenant del draft');
  }

  const body = await readJsonBody<{ client_comment?: string }>(ctx.req);
  const comment = typeof body.client_comment === 'string' ? body.client_comment.trim() : '';
  if (comment.length === 0) {
    throw new ValidationError('client_comment requerido para solicitar cambios');
  }

  // Persistir comentario en el campo `highlights` del draft para que el admin lo vea.
  // Formato: JSON con array de comentarios timestamped — soporta múltiples rondas.
  let existingComments: Array<{ at: string; text: string }> = [];
  try {
    if (draft.highlights) {
      const parsed = JSON.parse(draft.highlights);
      if (parsed && Array.isArray(parsed.client_comments)) {
        existingComments = parsed.client_comments;
      }
    }
  } catch { /* ignore parse error, sobreescribimos */ }
  existingComments.push({ at: now(), text: comment.slice(0, 500) });
  const newHighlights = JSON.stringify({ client_comments: existingComments });

  await datastore(ctx.req).table(TABLE).updateRow({
    ROWID: draftId,
    status: 'pending_client_review',
    highlights: newHighlights,
    updated_at: now(),
  });

  try {
    const { publishOutboxEvent } = await import('./outbox.js');
    await publishOutboxEvent(ctx.req, 'draft.client_requested_changes', {
      tenant_id: draft.tenant_id,
      draft_id: draftId,
      client_email: draft.client_email,
      client_comment: comment.slice(0, 500),
    });
  } catch (err) {
    log.warn('draft request-changes outbox publish failed', { error: (err as Error).message });
  }

  void (async () => {
    const { recordPortalSnapshot } = await import('./jobTracking.js');
    await recordPortalSnapshot(ctx, {
      tenantId: draft.tenant_id,
      eventType: 'portal.draft_rejected',
      portalToken: token,
      eventData: { draft_id: draftId },
    });
  })();

  log.info('draft changes requested by client', { draftId });
  sendJson(ctx.res, 200, { ok: true, status: 'pending_client_review' });
}

// ===== Admin: ver comentarios del cliente desde OutboxEvents =====

/**
 * GET /api/drafts/jobs/_recent_client_comments
 * Devuelve los últimos eventos `draft.client_requested_changes` con su payload.
 * Útil para ver comentarios viejos que se quedaron en outbox y no en el draft.
 */
export async function listRecentDraftComments(ctx: RequestContext): Promise<void> {
  const { requireAuth } = await import('../lib/auth.js');
  const { requireTenant } = await import('./tenants.js');
  await requireAuth(ctx);
  await requireTenant(ctx);

  try {
    const rows = unwrapRows<{ ROWID: string; event_type: string; payload: string | null; created_at: string }>(
      (await zcql(ctx.req).executeZCQLQuery(
        `SELECT ROWID, event_type, payload, created_at FROM OutboxEvents
         WHERE event_type = 'draft.client_requested_changes'
         ORDER BY CREATEDTIME DESC LIMIT 50`,
      )) as unknown[],
      'OutboxEvents',
    );

    const items = rows.map((r) => {
      let parsed: Record<string, unknown> = {};
      try { parsed = JSON.parse(r.payload ?? '{}'); } catch { /* ignore */ }
      return {
        id: r.ROWID,
        created_at: r.created_at,
        draft_id: parsed.draft_id,
        client_email: parsed.client_email,
        comment: parsed.client_comment,
      };
    });

    sendJson(ctx.res, 200, { items, count: items.length });
  } catch (err) {
    sendJson(ctx.res, 200, { items: [], count: 0, error: String((err as Error).message) });
  }
}

// ===== Helpers: builders de texto enriquecido para Recruit =====

function bulletList(items: unknown): string {
  if (!Array.isArray(items) || items.length === 0) return '';
  const cleaned = items.filter((x): x is string => typeof x === 'string' && x.trim().length > 0);
  if (cleaned.length === 0) return '';
  return '<ul>' + cleaned.map((x) => `<li>${escapeHtml(x)}</li>`).join('') + '</ul>';
}

function escapeHtml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

function buildJobDescriptionHtml(payload: Record<string, unknown>): string {
  const parts: string[] = [];
  const objetivo = typeof payload.objetivo_cargo === 'string' ? payload.objetivo_cargo : '';
  const context = typeof payload.context_summary === 'string' ? payload.context_summary : '';
  if (objetivo) parts.push(`<p><strong>Objetivo del cargo:</strong> ${escapeHtml(objetivo)}</p>`);
  if (context) parts.push(`<p>${escapeHtml(context)}</p>`);
  if (Array.isArray(payload.responsabilidades) && payload.responsabilidades.length > 0) {
    parts.push('<p><strong>Responsabilidades principales:</strong></p>');
    parts.push(bulletList(payload.responsabilidades));
  }
  if (Array.isArray(payload.tareas_especificas) && payload.tareas_especificas.length > 0) {
    parts.push('<p><strong>Tareas específicas:</strong></p>');
    parts.push(bulletList(payload.tareas_especificas));
  }
  return parts.join('');
}

function buildRequisitosHtml(payload: Record<string, unknown>): string {
  const parts: string[] = [];
  const formacion = typeof payload.formacion_requerida === 'string' ? payload.formacion_requerida : '';
  const experiencia = typeof payload.experiencia_requerida === 'string' ? payload.experiencia_requerida : '';
  if (formacion) parts.push(`<p><strong>Formación:</strong> ${escapeHtml(formacion)}</p>`);
  if (experiencia) parts.push(`<p><strong>Experiencia:</strong> ${escapeHtml(experiencia)}</p>`);
  if (Array.isArray(payload.herramientas_conocimientos) && payload.herramientas_conocimientos.length > 0) {
    parts.push('<p><strong>Herramientas y conocimientos técnicos:</strong></p>');
    parts.push(bulletList(payload.herramientas_conocimientos));
  }
  if (Array.isArray(payload.competencias) && payload.competencias.length > 0) {
    const compsArr = payload.competencias as Array<{ name?: string; required_pct?: number; que_evaluamos?: string }>;
    const compsItems = compsArr.map((c) => {
      const name = String(c.name ?? '').replace(/_/g, ' ');
      const detail = c.que_evaluamos ? ` — ${c.que_evaluamos}` : '';
      return `<li><strong>${escapeHtml(name)}</strong>${escapeHtml(detail)}</li>`;
    });
    parts.push('<p><strong>Competencias clave a evaluar:</strong></p>');
    parts.push('<ul>' + compsItems.join('') + '</ul>');
  }
  return parts.join('');
}

function buildVentajasHtml(payload: Record<string, unknown>): string {
  const parts: string[] = [];
  const salario = typeof payload.salario === 'string' ? payload.salario : '';
  const range = payload.salary_range_usd as { min?: number; max?: number } | undefined;
  const modalidad = typeof payload.modalidad === 'string' ? payload.modalidad : '';
  const viajes = typeof payload.viajes === 'string' ? payload.viajes : '';

  if (salario) {
    parts.push(`<p><strong>Salario:</strong> ${escapeHtml(salario)}</p>`);
  } else if (range && (range.min || range.max)) {
    parts.push(`<p><strong>Salario:</strong> USD ${range.min ?? 0} – ${range.max ?? 0}</p>`);
  }
  if (modalidad) parts.push(`<p><strong>Modalidad:</strong> ${escapeHtml(modalidad)}</p>`);
  if (viajes) parts.push(`<p><strong>Viajes:</strong> ${escapeHtml(viajes)}</p>`);
  if (Array.isArray(payload.disc_ventajas) && payload.disc_ventajas.length > 0) {
    parts.push('<p><strong>Lo que va a poder lograr en este puesto:</strong></p>');
    parts.push(bulletList(payload.disc_ventajas));
  }
  return parts.join('');
}

// ===== Helpers =====

async function fetchDraft(req: IncomingMessage, id: string, tenantId: string): Promise<JobProfileDraftRow | null> {
  const q = `SELECT * FROM ${TABLE} WHERE ROWID = '${escapeSql(id)}' AND tenant_id = '${escapeSql(tenantId)}' LIMIT 1`;
  const rows = unwrapRows<JobProfileDraftRow>(
    (await zcql(req).executeZCQLQuery(q)) as unknown[],
    TABLE,
  );
  return rows[0] ?? null;
}
